config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do 
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
  end

  scope '/admin' do
    resources :competitions, as: 'competitions' do
      post 'organize', on: :collection
      post 'numbers', on: :collection
      post 'next_state', on: :member
      post 'start_all', on: :member
      post 'start/:userid/:day', on: :member, to: :start
      post 'start1/:userid/:day', on: :member, to: :start_plus_one
      post 'mark_dns/:userid/:day', on: :member, to: :mark_dns
      post 'mark_dnf/:userid/:day', on: :member, to: :mark_dnf
      post 'mark_complete/:userid/:day', on: :member, to: :mark_complete
      post 'update_result/:userid/:day', on: :member, to: :update_result
      get 'print', on: :collection, to: :print
    end
    resources :cms, as: 'cms_block', controller: 'cms_blocks'
    resources :users, as: 'users' do
      get 'receipt', on: :member
    end
  end

  get 'competition', to: 'competitions#index'
  get 'cms/:id', to: 'cms_blocks#show'
  post '/apply', to: 'home#apply'

  root to: 'home#index'
end

app/models/cms_block.rb
class CmsBlock
  include Mongoid::Document
  field :name, type: String
  field :content, type: String
  
  def view
    MDParser.render(content).html_safe
  end
end

app/controllers/cms_blocks_controller.rb
class CmsBlocksController < ApplicationController
  before_action :set_cms_block, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show

  # GET /cms_blocks
  # GET /cms_blocks.json
  def index
    @cms_blocks = CmsBlock.all
  end

  # GET /cms_blocks/1
  # GET /cms_blocks/1.json
  def show
  end

  # GET /cms_blocks/new
  def new
    @cms_block = CmsBlock.new
  end

  # GET /cms_blocks/1/edit
  def edit
  end

  # POST /cms_blocks
  # POST /cms_blocks.json
  def create
    check_admin
    @cms_block = CmsBlock.new(cms_block_params)

    respond_to do |format|
      if @cms_block.save
        format.html { redirect_to @cms_block, notice: 'Cms block was successfully created.' }
        format.json { render :show, status: :created, location: @cms_block }
      else
        format.html { render :new }
        format.json { render json: @cms_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cms_blocks/1
  # PATCH/PUT /cms_blocks/1.json
  def update
    check_admin
    respond_to do |format|
      if @cms_block.update(cms_block_params)
        format.html { redirect_to @cms_block, notice: 'Cms block was successfully updated.' }
        format.json { render :show, status: :ok, location: @cms_block }
      else
        format.html { render :edit }
        format.json { render json: @cms_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms_blocks/1
  # DELETE /cms_blocks/1.json
  def destroy
    check_admin
    @cms_block.destroy
    respond_to do |format|
      format.html { redirect_to cms_blocks_url, notice: 'Cms block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_cms_block
      # try to find the block by name and then by id
      puts "Searching for #{params[:id]}"
      @cms_block = CmsBlock.where(name: params[:id])[0] 
      @cms_block ||= CmsBlock.find(params[:id])
      puts "Found: #{@cms_block}"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cms_block_params
      params.require(:cms_block).permit(:name, :content)
    end
end

app/helpers/cms_blocks_helper.rb
module CmsBlocksHelper
  def cms_blocks_path format
    @cms_block.new_record? ? cms_block_index_path : cms_block_path(@cms_block.id)
  end
end

app/views/cms_blocks/_form.html.haml
= bootstrap_form_for @cms_block do |f|
  - if @cms_block.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cms_block.errors.count, "error")} prohibited this cms_block from being saved:"
      %ul
        - @cms_block.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name
  .field
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/cms_blocks/edit.html.haml
%h1 Editing cms_block

= render 'form'

= link_to 'Show', @cms_block
\|
= link_to 'Back', cms_block_index_path

app/views/cms_blocks/index.html.haml
%h1 Listing cms_blocks

%table.table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @cms_blocks.each do |cms_block|
      %tr
        %td= link_to cms_block.name, cms_block 
        %td= cms_block.content[0,100] + (cms_block.content.length > 100 ? "..." : "")
        %td= link_to 'Edit', edit_cms_block_path(cms_block)
        %td= link_to 'Destroy', cms_block, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cms block', new_cms_block_path

app/views/cms_blocks/new.html.haml
%h1 New cms_block

= render 'form'

= link_to 'Back', cms_block_index_path

app/views/cms_blocks/show.html.haml
%p#notice= notice

%h1= @cms_block.name
.cms_content(style="padding: 6px; border: solid 1px gray;")= @cms_block.view

= link_to 'Edit', edit_cms_block_path(@cms_block)
\|
= link_to 'Back', cms_block_index_path