config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do 
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
  end

  scope '/admin' do
    resources :competitions, as: 'competitions' do
      post 'organize', on: :collection
      post 'numbers', on: :collection
      post 'next_state', on: :member
      post 'start_all', on: :member
      post 'start/:userid/:day', on: :member, to: :start
      post 'start1/:userid/:day', on: :member, to: :start_plus_one
      post 'mark_dns/:userid/:day', on: :member, to: :mark_dns
      post 'mark_dnf/:userid/:day', on: :member, to: :mark_dnf
      post 'mark_complete/:userid/:day', on: :member, to: :mark_complete
      post 'update_result/:userid/:day', on: :member, to: :update_result
      get 'print', on: :collection, to: :print
    end
    resources :cms, as: 'cms_block', controller: 'cms_blocks'
    resources :users, as: 'users' do
      get 'receipt', on: :member
    end
  end

  get 'competition', to: 'competitions#index'
  get 'cms/:id', to: 'cms_blocks#show'
  post '/apply', to: 'home#apply'

  root to: 'home#index'
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy, :next_state,
                                         :start_all, :start, :start_plus_one, :mark_dns, :mark_dnf,
                                         :mark_complete, :update_result]
  before_action :set_competitor, only: [:start, :start_plus_one, :mark_dns, :mark_dnf,
                                         :mark_complete, :update_result]
  before_action :authenticate_user!, except: [:show, :index, :print]

  
  def print
    @print = true
    index
  end
  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all.order_by(order_number: :asc)
    respond_to do |format|
      format.html do
        @total_competitors = @competitions.inject(0){|sum,x| sum + (x[:list].nil? ? 0 : x[:list].length) }
        render :index
      end
      format.json { render json: @competitions.as_json }
    end
  end
  
  def numbers
    check_admin
    result = update_numbers(params)
    respond_to do |format|
      format.html { redirect_to competitions_path, notice: result }
      format.json { render :show, status: :created, location: @competition }
    end
  end
  
  def next_state
    puts "changing state from #{@competition.state} to #{@competition.next_state}"
    @competition.next_state!
    puts "state is now #{Competition.find(params[:id]).state}"
    respond_to do |format|
      format.html { redirect_to competitions_path, notice: "State changed to #{@competition.state}" }
      format.json { render :show, status: :created, location: @competition }
    end
  end
  
  def organize
    check_admin
    results = perform_reorganization
    if results.blank?
      notice = "Competition reorganization done, no change!"
    else
      notice = results.slice(0,10).join("<br/>").html_safe
    end
    notice += "<br/>... and more" if results.length > 11

    respond_to do |format|
      format.html { redirect_to competitions_path, notice: notice }
      format.json { render :show, status: :created, location: @competition }
    end
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @competition.as_json }
    end
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    check_admin
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to competitions_path, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    check_admin
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to competitions_path, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    check_admin
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def start_all
    check_admin
    puts "Starting all for competition #{@competition.name} on day #{params[:day]}"
    @competition.start_all!(params[:day].to_i)
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "Mass start in #{@competition.name}." }
      format.json { head :no_content }
    end
  end
  
  def start
    check_admin
    puts "Starting #{@competitor[:name]} for competition #{@competition.name} on day #{params[:day]}"
    @competition.start! @competitor, params[:day].to_i, nil
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "#{@competitor[:name]} started in #{@competition.name}." }
      format.json { head :no_content }
    end
  end

  def start_plus_one
    check_admin
    puts "Starting after a minute #{@competitor[:name]} for competition #{@competition.name} on day #{params[:day]}"
    @competition.start_plus_one! @competitor, params[:day].to_i
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "#{@competitor[:name]} started in #{@competition.name} one minute after previous." }
      format.json { head :no_content }
    end
  end

  def mark_dns
    check_admin
    puts "#{@competitor[:name]} marked :dns in #{@competition.name}."
    @competition.mark_dns! @competitor, params[:day].to_i
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "#{@competitor[:name]} marked :dns in #{@competition.name}." }
      format.json { head :no_content }
    end
  end
  def mark_dnf
    check_admin
    puts "#{@competitor[:name]} marked :dnf in #{@competition.name}."
    @competition.mark_dnf! @competitor, params[:day].to_i
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "#{@competitor[:name]} marked :dnf in #{@competition.name}." }
      format.json { head :no_content }
    end
  end
  def mark_complete
    check_admin
    puts "#{@competitor[:name]} passed through FINISH #{@competition.name}."
    @competition.mark_complete! @competitor, params[:day].to_i
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "#{@competitor[:name]} passed through FINISH #{@competition.name}." }
      format.json { head :no_content }
    end
  end
  def update_result
    check_admin
    @competition.update_result! @competitor, params[:new_status], params[:day].to_i
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "#{@competitor[:name]} updated status to #{params[:new_status]}" }
      format.json { head :no_content }
    end
  end
private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end
    
    def set_competitor
      @competitor = @competition[:list].select{ |c| c[:id].to_s == params[:userid]}[0]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:code, :name, :type, :order_number, :state)
    end
    
    def to_new_code(maybe_old_code)
        maybe_old_code
          .gsub(" SM", "")
          .gsub("NMS1", "SM1 ")
          .gsub("NWS1", "SW1 ")
          .gsub("Veteraani Miehet", "SM1 veteraani")
          .gsub("Veteraani Naiset", "SW1 veteraani")
          .gsub("NMSJ A/B", "SMj B")
    end
    
    def perform_reorganization
      results = []
      # first, go through competitions and competitors, and check that each should be in the application
      Competition.each do |competition|
        if competition[:list] and competition[:list].reject! { |competitor|
              begin
                res = User.find(competitor[:id])[:races].none? {|r| to_new_code(r).gsub("SM ","") == competition.code.gsub("SM ","")} 
                results << "Removing #{competitor[:name]} from #{competition[:code]}" if res
                res
              rescue
                results << "Removing deleted user #{competitor[:name]} from #{competition[:code]}"
                true
              end
            }
          Competition.collection.find(_id: competition._id).update("$set" => { list: competition[:list]})
        end
      end
      # second, go through all the users and their applied for races, and add them if they are not already added
      User.all.each do |user| user[:races].each do |c|
          competition = begin Competition.find_by(code: to_new_code(c)) rescue Competition.find_by(code: "SM #{to_new_code(c)}") end
          competition[:list] ||= []
          if competition[:list].none? {|cc| cc[:id] == user.id}
            results << "Adding #{user[:name].titleize} to #{competition.code}"
            competition[:list] << {
              id: user.id,
              num: (competition[:list].map{|x| x[:num]}.max or 0) + 1,
              name: user.name,
              club: user.club,
              dogs: user[:dogs],
            }
            Competition.collection.find(_id: competition._id).update("$set" => { list: competition[:list]})
          end
        end
      end
      results
    end
    
    def update_numbers(data)
      result = 0
      data.each do |key, value| 
        unless (ident = key.split("$")).blank? or ident[0] != "number"
          competition = Competition.find_by(code: ident[1])
          changed = false
          competition[:list].map do |competitor|
            if competitor[:id].to_s == ident[2].to_s
              if competitor[:num].to_i != value.to_i
                puts "Changing #{competitor[:name]} in #{competition[:code]} from #{competitor[:num]} to #{value}"
                competitor[:num] = value.to_i
                result += 1
                changed = true
              end
            end
            competitor
          end
          if changed
            #following will sort the list by start number and save it
            competition.save_info!
          end
        end
      end
      "Changed #{result} numbers."
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.haml
= bootstrap_form_for @competition do |f|
  - if @competition.errors.any?
    #error_explanation
      %h2= "#{pluralize(@competition.errors.count, "error")} prohibited this competition from being saved:"
      %ul
        - @competition.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.number_field :order_number
  .field
    = f.text_field :code
  .field
    = f.text_field :name
  .field
    = f.select :type, ['single run', 'two runs combined'], { prompt: "Select a type" }
  .field
    = f.select :state, [:open, :ready, :active, :done, :closed], { prompt: "Select a state" }
  .actions
    = f.submit 'Save'

app/views/competitions/_manage.html.haml
%h3 #{competition.code} - #{competition.name}
-if user_signed_in? and current_user.admin? and active_list and not competition.type == "two runs combined"
  -if competition[:list] and competition[:list].all? {|competitor| competition.final_result(competitor).nil?}
    = link_to("/admin/competitions/#{competition.id}/start_all", :method => :post) do
      %button.btn.btn-default Start all
%p
  -unless @print
    %span Competitors:
    %strong=competition[:list].length
.row(style="font-weight: bold")
  .col-xs-1 #
  .col-xs-3.col-sm-3.col-lg-2 Nimi
  -if competition.state and competition.had_started
    -if competition.type == "two runs combined"
      .col-xs-2.score Päivä 1
      .col-xs-2.score Päivä 2
      .col-xs-2.score Yhteissä
    -else
      .col-xs-6.col-lg-4.score Aika
    .col-xs-2.score Tulos
- competition[:list].each do |competitor|
  .row.competitor-info(style="border-top: solid 1px #ccc")
    .col-xs-1.col-sm-1.col-lg-1
      -if user_signed_in? and current_user.admin? and not active_list
        .form-group
          =number_field_tag "number$#{competition.code}$#{competitor[:id]}", competitor[:num], {class: "form-control input-sm"}
      -else
        = competitor[:num]
    .col-xs-3.col-sm-3.col-lg-2= competitor[:name].titleize + ", #{competitor[:club]}"
    -if competition.state and competition.had_started
      -if competition.type == "two runs combined"
        .col-xs-2= render 'result', competition: competition, competitor: competitor, day: 1, active_list: active_list
        .col-xs-2= render 'result', competition: competition, competitor: competitor, day: 2, active_list: active_list
        .col-xs-2= render 'result', competition: competition, competitor: competitor, day: 0, active_list: active_list
      -else
        .col-xs-6.col-lg-4=render 'result', competition: competition, competitor: competitor, day: 0, active_list: active_list
      .col-xs-2.col-md-2.score
        =competition.competitor_score competitor
        
        

app/views/competitions/_result.html.haml
-# competition: competition, competitor: competitor, day: 1
-if user_signed_in? and current_user.admin? and (day != 0 or competition.type != "two runs combined")
  -if active_list
    .form-group
      -if competition.state.to_sym == :active
        -unless competition.result(competitor, day) and competition.result(competitor, day) != :none
          = link_to("/admin/competitions/#{competition.id}/start/#{competitor[:id]}/#{day}", :method => :post) do
            %button.btn.btn-default.btn-sm start
          -if competition.can_start_plus_one!(competitor, day)
            = link_to("/admin/competitions/#{competition.id}/start1/#{competitor[:id]}/#{day}", :method => :post) do
              %button.btn.btn-default.btn-sm start + 1
          = link_to("/admin/competitions/#{competition.id}/mark_dns/#{competitor[:id]}/#{day}", :method => :post) do
            %button.btn.btn-default.btn-sm dns!
        -if competition.result(competitor, day) == :started
          = link_to("/admin/competitions/#{competition.id}/mark_complete/#{competitor[:id]}/#{day}", :method => :post) do
            %button.btn.btn-default.btn-sm finish!
          = link_to("/admin/competitions/#{competition.id}/mark_dnf/#{competitor[:id]}/#{day}", :method => :post) do
            %button.btn.btn-default.btn-sm dnf
      =form_tag("/admin/competitions/#{competition.id}/update_result/#{competitor[:id]}/#{day}", method: "post", class: "form form-inline") do 
        =text_field_tag "new_status", competition.result(competitor, day), {class: "form-control input-sm"}
        %button.btn.btn-default.btn-sm Update
  -else
    =form_tag("/admin/competitions/#{competition.id}/update_result/#{competitor[:id]}/#{day}", method: "post", class: "form form-inline") do 
      =text_field_tag "new_status", competition.result(competitor, day), {class: "form-control input-sm"}
      %button.btn.btn-default.btn-sm Update
%p.score
  %span=competition.result competitor, day
  -#if (competition.result(competitor, day) == :started) and (t=competitor[:result][day-1][:start_time])
    %span=t.strftime "%T.%1L"

app/views/competitions/edit.html.haml
%h1 Editing competition

= render 'form'

= link_to 'Show', @competition
\|
= link_to 'Back', competitions_path

app/views/competitions/index.html.haml
-unless @print
  - if @competitions.any? {|c| c.state and c.state.to_sym == :active }
    %h1 Active competitions
    - @competitions.each do |competition|
      -if competition.state and competition.state.to_sym == :active
        = render 'manage', competition: competition, active_list: true

=form_tag("/admin/competitions/numbers", method: "post") do
  -unless @print
    %h1 Listing competitions

    %p
      %span Total competitors:
      %strong=@total_competitors

    -if user_signed_in? and current_user.admin?
      = link_to("/admin/competitions/organize", :method => :post) do
        %button.btn.btn-default Reorganize competitions
      = submit_tag "Update start numbers", {class: "btn btn-default"}

    .row(style="font-weight: bold")
      -if user_signed_in? and current_user.admin?
        .col-xs-3.col-sm-1 Order
      .col-xs-3.col-sm-2 Code
      .col-xs-3.col-sm-3 Name
      .col-xs-3.col-sm-2 Type
      .col-xs-3.col-sm-2 State
    - @competitions.each do |competition|
      .row(style="border-top: solid 1px #ccc")
        -if user_signed_in? and current_user.admin?
          .col-xs-3.col-sm-1= competition.order_number
        .col-xs-3.col-sm-2= link_to competition.code, edit_competition_path(competition)
        .col-xs-3.col-sm-3= competition.name
        .col-xs-3.col-sm-2= competition.type[0,12]
        .col-xs-3.col-sm-2= competition.state or "open"
        -if user_signed_in? and current_user.admin?
          .hidden-xs.col-sm-2
            -if competition.next_state
              = link_to "Change to #{competition.next_state}", "/admin/competitions/#{competition._id}/next_state", :method => :post
            = link_to 'Destroy', competition, :method => :delete, :data => { :confirm => 'Are you sure?' }

  -if user_signed_in? and current_user.admin?
    %br
    #span(style="font-weight: bold")= link_to 'New Competition', new_competition_path

  %h1 Taivalsprintti 2015
  - @competitions.each do |competition|
    -unless competition[:list].nil?
      =render 'manage', competition: competition, active_list: false

app/views/competitions/new.html.haml
%h1 New competition

= render 'form'

= link_to 'Back', competitions_path

app/views/competitions/show.html.haml
%p#notice= notice

%p
  %b Code:
  = @competition.code
%p
  %b Name:
  = @competition.name
%p
  %b Type:
  = @competition.type

= link_to 'Edit', edit_competition_path(@competition)
\|
= link_to 'Back', competitions_path

%h3 Start list

-if @competition[:list].nil?
  %p No start list has been done yet
-else
  %table.table
    %thead
      %tr
        %th Number
        %th Name
        %th Club
        %th Dogs
    %tbody
      - @competition[:list].each do |competitor|
        %tr
          %td= competitor[:num]
          %td= competitor[:name]
          %td= competitor[:club]
          %td= competitor[:dogs]